"use client";
import { useActionState, useState } from "react";
import { Loader2, Search } from "lucide-react";
import { toast } from "sonner";
import { createManga } from "@/actions/mangas";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { Alert, AlertDescription } from "@/components/ui/alert";
import type { UrlMangaIdentification } from "@/types/manga";
export function AddMangaForm() { const [metadata, setMetadata] = useState<UrlMangaIdentification | null>(null); const [url, setUrl] = useState(""); const [extracting, setExtracting] = useState(false); const [state, action, pending] = useActionState(createManga, {}); async function extract() { setExtracting(true); try { const response = await fetch("/api/extraction", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ url }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error); setMetadata(json); toast.success("URL identifiée. Vérifiez les informations avant l’enregistrement."); } catch (error) { toast.error(error instanceof Error ? error.message : "Identification impossible"); setMetadata({ mangaTitle: null, canonicalUrl: url, sourceName: new URL(url).hostname, currentChapter: null, confidence: 0, warnings: ["Complétez manuellement les informations."] }); } finally { setExtracting(false); } }
  if (!metadata) return <Card><CardHeader><CardTitle>Ajouter depuis une URL</CardTitle><CardDescription>Ajoutez l’URL du chapitre que vous lisez actuellement.</CardDescription></CardHeader><CardContent><div className="flex flex-col gap-3 sm:flex-row"><Input type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://exemple.com/manga/.../chapter/158" required /><Button onClick={extract} disabled={extracting || !url}>{extracting ? <Loader2 className="animate-spin" /> : <Search />}Analyser</Button></div></CardContent></Card>;
  const current = metadata.currentChapter; return <form action={action} className="space-y-6"><Card><CardHeader><CardTitle>Confirmer les informations</CardTitle><CardDescription>Le site, le manga et votre chapitre actuel ont été déduits uniquement de l’URL.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Field label="Titre" name="title" defaultValue={metadata.mangaTitle ?? ""} required /><Field label="URL de la série" name="canonicalUrl" defaultValue={metadata.canonicalUrl} type="url" required /><Field label="Source" name="sourceName" defaultValue={metadata.sourceName} required /><div><Label htmlFor="status">Statut</Label><select id="status" name="status" defaultValue="reading" className="mt-1 h-9 w-full rounded-lg border bg-background px-3 text-sm"><option value="reading">En lecture</option><option value="planned">À lire</option><option value="paused">En pause</option><option value="completed">Terminé</option><option value="dropped">Abandonné</option></select></div><Field label="Chapitre actuel (lu)" name="chapterLabel" defaultValue={current?.label ?? ""} required /><Field label="Numéro du chapitre actuel" name="chapterNumber" type="number" step="0.01" defaultValue={current?.number ?? ""} required /><Field label="URL du chapitre actuel" name="chapterUrl" type="url" defaultValue={current?.url ?? url} required /><div><Label>Chapitre détecté dans l’URL</Label><Input value={current?.label ?? "Non détecté"} readOnly className="mt-1 bg-muted" /></div><div><Label htmlFor="rating">Évaluation /10</Label><Input id="rating" name="rating" type="number" min="0" max="10" className="mt-1" /></div><div className="flex items-center gap-3 pt-6"><Switch id="notificationsEnabled" name="notificationsEnabled" /><Label htmlFor="notificationsEnabled">Notifications pour ce manga</Label></div><div className="md:col-span-2"><Label htmlFor="notes">Note personnelle</Label><Textarea id="notes" name="notes" maxLength={5000} className="mt-1" /></div>{metadata.warnings.length > 0 && <Alert className="md:col-span-2"><AlertDescription>{metadata.warnings.join(" ")}</AlertDescription></Alert>}{state.error && <Alert variant="destructive" className="md:col-span-2"><AlertDescription>{state.error}</AlertDescription></Alert>}</CardContent></Card><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => setMetadata(null)}>Retour</Button><Button disabled={pending}>{pending ? "Enregistrement…" : "Ajouter à la bibliothèque"}</Button></div></form>; }
function Field({ label, name, ...props }: React.ComponentProps<typeof Input> & { label: string; name: string }) { return <div><Label htmlFor={name}>{label}</Label><Input id={name} name={name} className="mt-1" {...props} /></div>; }
