/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { ExternalLink } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { MangaListItem } from "@/types/manga";
import { NotificationToggle } from "./notification-toggle";
const labels = { reading: "En lecture", planned: "À lire", paused: "En pause", completed: "Terminé", dropped: "Abandonné" } as const;
export function MangaCard({ manga }: { manga: MangaListItem }) { const latest = manga.chapters?.[0]; const read = manga.reading_progress?.[0]?.last_read_number ?? 0; const unread = latest?.number_normalized ? Math.max(0, Math.floor(latest.number_normalized - read)) : 0; return <Card className="overflow-hidden transition hover:-translate-y-0.5 hover:shadow-md"><CardHeader className="pb-3"><div className="flex items-start gap-3"><div className="grid size-12 shrink-0 place-items-center overflow-hidden rounded-lg bg-muted">{(manga as MangaListItem & { cover_image_url?: string | null }).cover_image_url ? <img src={(manga as MangaListItem & { cover_image_url?: string | null }).cover_image_url!} alt="" className="size-full object-cover" /> : <span className="text-xs">MT</span>}</div><div className="min-w-0 flex-1"><CardTitle className="truncate text-base"><Link href={`/mangas/${manga.id}`} className="hover:text-primary">{manga.title}</Link></CardTitle><p className="mt-1 truncate text-xs text-muted-foreground">{manga.source_name}</p></div><NotificationToggle mangaId={manga.id} enabled={manga.notifications_enabled} /></div></CardHeader><CardContent><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary">{labels[manga.status]}</Badge>{unread > 0 && <Badge>{unread} non lu{unread > 1 ? "s" : ""}</Badge>}</div><div className="mt-5 flex items-end justify-between"><div><p className="text-xs text-muted-foreground">Dernier chapitre</p><p className="font-mono text-sm font-medium">{latest?.number_label ?? "Inconnu"}</p></div><Link href={`/mangas/${manga.id}`} aria-label={`Ouvrir ${manga.title}`}><ExternalLink className="size-4" /></Link></div></CardContent></Card>; }
