import Link from "next/link";
import { notFound } from "next/navigation";
import { ExternalLink } from "lucide-react";
import { archiveManga, updateProgress } from "@/actions/mangas";
import { requireUser } from "@/lib/supabase/auth";
import { createClient } from "@/lib/supabase/server";
import { Badge } from "@/components/ui/badge";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckButton } from "@/features/mangas/check-button";
export default async function MangaDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const user = await requireUser(); const supabase = await createClient(); const { data: manga } = await supabase.from("mangas").select("*,chapters(*),reading_progress(*)").eq("id", id).eq("user_id", user.id).single(); if (!manga) notFound(); const chapters = [...(manga.chapters ?? [])].sort((a, b) => (b.number_normalized ?? -1) - (a.number_normalized ?? -1)); return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Badge variant="secondary">{manga.status}</Badge><span className="text-sm text-muted-foreground">{manga.source_name}</span></div><h1 className="mt-2 text-3xl font-semibold tracking-tight">{manga.title}</h1><a href={manga.canonical_url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex items-center gap-1 text-sm text-primary hover:underline">{new URL(manga.canonical_url).hostname}<ExternalLink className="size-3" /></a></div><div className="flex gap-2"><CheckButton id={id} /><form action={archiveManga.bind(null, id)}><Button variant="destructive">Archiver</Button></form></div></div>{manga.last_check_error && <div className="mt-6 rounded-lg border border-destructive/30 bg-destructive/10 p-4 text-sm">Dernière erreur : {manga.last_check_error}</div>}<div className="mt-6 grid gap-6 lg:grid-cols-[2fr_1fr]"><Card><CardHeader><CardTitle>Chapitres détectés</CardTitle></CardHeader><CardContent>{chapters.length ? <div className="divide-y">{chapters.map((chapter) => <div key={chapter.id} className="flex items-center justify-between gap-3 py-3"><div><p className="font-medium">{chapter.number_label}</p>{chapter.title && <p className="text-sm text-muted-foreground">{chapter.title}</p>}</div><div className="flex gap-2"><form action={updateProgress.bind(null, id, chapter.id, chapter.number_normalized)}><Button size="sm" variant="outline">Marquer lu</Button></form><Link href={chapter.url} target="_blank" rel="noopener noreferrer" className={buttonVariants({ size: "sm" })}>Ouvrir</Link></div></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">Aucun chapitre enregistré.</p>}</CardContent></Card><div className="space-y-6"><Card><CardHeader><CardTitle>Progression</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Dernier chapitre lu</p><p className="mt-1 font-mono text-2xl font-semibold">{manga.reading_progress?.[0]?.last_read_number ?? "—"}</p></CardContent></Card><Card><CardHeader><CardTitle>Votre avis</CardTitle></CardHeader><CardContent><p className="font-mono text-2xl">{manga.rating === null ? "—" : `${manga.rating}/10`}</p><p className="mt-3 whitespace-pre-wrap text-sm text-muted-foreground">{manga.notes || "Aucune note personnelle."}</p></CardContent></Card></div></div></div>; }
