import Link from "next/link";
import { Library } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { requireUser } from "@/lib/supabase/auth";
import { MangaCard } from "@/features/mangas/manga-card";
import { Input } from "@/components/ui/input";
import { buttonVariants } from "@/components/ui/button";
import type { MangaListItem } from "@/types/manga";
export default async function MangasPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) { const user = await requireUser(); const filters = await searchParams; const supabase = await createClient(); let query = supabase.from("mangas").select("id,title,source_name,status,rating,notifications_enabled,last_checked_at,last_check_status,chapters(id,number_label,number_normalized,url,detected_at),reading_progress(last_read_number)").eq("user_id", user.id).is("archived_at", null).order("updated_at", { ascending: false }).limit(50); if (filters.q) query = query.ilike("title", `%${filters.q.replace(/[%,]/g, "")}%`); if (filters.status) query = query.eq("status", filters.status); const { data } = await query; const mangas = (data ?? []) as MangaListItem[]; return <div><div className="flex items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Bibliothèque</h1><p className="mt-1 text-sm text-muted-foreground">{mangas.length} manga{mangas.length > 1 ? "s" : ""} affiché{mangas.length > 1 ? "s" : ""}</p></div><Link href="/mangas/new" className={buttonVariants()}>Ajouter</Link></div><form className="my-6 flex gap-2"><Input name="q" defaultValue={filters.q} placeholder="Rechercher un titre…" /><select name="status" defaultValue={filters.status ?? ""} className="h-9 rounded-lg border bg-background px-3 text-sm"><option value="">Tous les statuts</option><option value="reading">En lecture</option><option value="planned">À lire</option><option value="paused">En pause</option><option value="completed">Terminé</option></select></form>{mangas.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{mangas.map((manga) => <MangaCard key={manga.id} manga={manga} />)}</div> : <div className="grid min-h-72 place-items-center rounded-xl border border-dashed text-center"><div><Library className="mx-auto mb-4 size-10 text-muted-foreground" /><h2 className="font-medium">Bibliothèque vide</h2><p className="mt-1 mb-4 text-sm text-muted-foreground">Ajoutez votre premier manga à partir de son URL.</p><Link href="/mangas/new" className={buttonVariants()}>Ajouter un manga</Link></div></div>}</div>; }
