begin;
create extension if not exists pgcrypto;
create type public.manga_status as enum ('reading','planned','paused','completed','dropped');
create type public.check_status as enum ('unchanged','new_chapter','ambiguous','failed','rate_limited');

create function public.set_updated_at() returns trigger language plpgsql security invoker set search_path = '' as $$ begin new.updated_at = timezone('utc', now()); return new; end; $$;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text check (char_length(display_name) <= 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.mangas (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null check (char_length(title) between 1 and 300), canonical_url text not null check (canonical_url ~ '^https?://'), source_name text not null check (char_length(source_name) between 1 and 120), status public.manga_status not null default 'reading', notes text check (char_length(notes) <= 5000), rating smallint check (rating between 0 and 10), notifications_enabled boolean not null default false, last_checked_at timestamptz, last_successful_check_at timestamptz, last_check_status public.check_status, last_check_error text check (char_length(last_check_error) <= 500), consecutive_failures integer not null default 0 check (consecutive_failures >= 0), next_check_at timestamptz, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (user_id, canonical_url), unique (id, user_id));
create table public.chapters (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, manga_id uuid not null, number_label text not null check (char_length(number_label) between 1 and 100), number_normalized numeric(12,3), title text check (char_length(title) <= 300), url text not null check (url ~ '^https?://'), published_at timestamptz, detected_at timestamptz not null default now(), is_read boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key (manga_id,user_id) references public.mangas(id,user_id) on delete cascade, unique (manga_id,url), unique (id,user_id));
create table public.reading_progress (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, manga_id uuid not null, last_read_chapter_id uuid, last_read_number numeric(12,3), mark_opened_as_read boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key (manga_id,user_id) references public.mangas(id,user_id) on delete cascade, foreign key (last_read_chapter_id,user_id) references public.chapters(id,user_id) on delete set null, unique(user_id,manga_id));
create table public.categories (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null check (char_length(name) between 1 and 80), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,name), unique(id,user_id));
create table public.manga_categories (user_id uuid not null references auth.users(id) on delete cascade, manga_id uuid not null, category_id uuid not null, created_at timestamptz not null default now(), primary key(manga_id,category_id), foreign key(manga_id,user_id) references public.mangas(id,user_id) on delete cascade, foreign key(category_id,user_id) references public.categories(id,user_id) on delete cascade);
create table public.push_subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, endpoint text not null check(char_length(endpoint) <= 2048), p256dh text not null, auth_key text not null, user_agent text check(char_length(user_agent) <= 500), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,endpoint));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, manga_id uuid not null, chapter_id uuid not null, title text not null check(char_length(title) <= 300), body text not null check(char_length(body) <= 500), target_path text not null check(target_path ~ '^/mangas/[0-9a-f-]+$'), read_at timestamptz, push_sent_at timestamptz, created_at timestamptz not null default now(), foreign key(manga_id,user_id) references public.mangas(id,user_id) on delete cascade, foreign key(chapter_id,user_id) references public.chapters(id,user_id) on delete cascade, unique(user_id,manga_id,chapter_id));
create table public.manga_check_logs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, manga_id uuid not null, status public.check_status not null, error_message text check(char_length(error_message) <= 500), warnings jsonb not null default '[]'::jsonb check(jsonb_typeof(warnings)='array'), duration_ms integer check(duration_ms >= 0), checked_at timestamptz not null default now(), foreign key(manga_id,user_id) references public.mangas(id,user_id) on delete cascade);
create table public.user_settings (user_id uuid primary key references auth.users(id) on delete cascade, notifications_enabled boolean not null default true, notify_on_check_errors boolean not null default false, mark_opened_as_read boolean not null default false, theme text not null default 'system' check(theme in ('light','dark','system')), locale text not null default 'fr', created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index mangas_due_check_idx on public.mangas(next_check_at) where archived_at is null;
create index mangas_user_status_idx on public.mangas(user_id,status) where archived_at is null;
create index chapters_manga_number_idx on public.chapters(manga_id,number_normalized desc nulls last);
create index chapters_user_unread_idx on public.chapters(user_id,detected_at desc) where is_read=false;
create index notifications_user_unread_idx on public.notifications(user_id,created_at desc) where read_at is null;
create index check_logs_manga_date_idx on public.manga_check_logs(manga_id,checked_at desc);

create trigger profiles_updated before update on public.profiles for each row execute function public.set_updated_at();
create trigger mangas_updated before update on public.mangas for each row execute function public.set_updated_at();
create trigger chapters_updated before update on public.chapters for each row execute function public.set_updated_at();
create trigger progress_updated before update on public.reading_progress for each row execute function public.set_updated_at();
create trigger categories_updated before update on public.categories for each row execute function public.set_updated_at();
create trigger subscriptions_updated before update on public.push_subscriptions for each row execute function public.set_updated_at();
create trigger settings_updated before update on public.user_settings for each row execute function public.set_updated_at();

create function public.handle_new_user() returns trigger language plpgsql security definer set search_path = '' as $$ begin insert into public.profiles(id) values(new.id); insert into public.user_settings(user_id) values(new.id); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security; alter table public.mangas enable row level security; alter table public.chapters enable row level security; alter table public.reading_progress enable row level security; alter table public.categories enable row level security; alter table public.manga_categories enable row level security; alter table public.push_subscriptions enable row level security; alter table public.notifications enable row level security; alter table public.manga_check_logs enable row level security; alter table public.user_settings enable row level security;

create policy profiles_select on public.profiles for select to authenticated using ((select auth.uid())=id); create policy profiles_insert on public.profiles for insert to authenticated with check ((select auth.uid())=id); create policy profiles_update on public.profiles for update to authenticated using ((select auth.uid())=id) with check ((select auth.uid())=id); create policy profiles_delete on public.profiles for delete to authenticated using ((select auth.uid())=id);
create policy mangas_select on public.mangas for select to authenticated using ((select auth.uid())=user_id); create policy mangas_insert on public.mangas for insert to authenticated with check ((select auth.uid())=user_id); create policy mangas_update on public.mangas for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy mangas_delete on public.mangas for delete to authenticated using ((select auth.uid())=user_id);
create policy chapters_select on public.chapters for select to authenticated using ((select auth.uid())=user_id); create policy chapters_insert on public.chapters for insert to authenticated with check ((select auth.uid())=user_id and exists(select 1 from public.mangas m where m.id=manga_id and m.user_id=(select auth.uid()))); create policy chapters_update on public.chapters for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy chapters_delete on public.chapters for delete to authenticated using ((select auth.uid())=user_id);
create policy progress_select on public.reading_progress for select to authenticated using ((select auth.uid())=user_id); create policy progress_insert on public.reading_progress for insert to authenticated with check ((select auth.uid())=user_id and exists(select 1 from public.mangas m where m.id=manga_id and m.user_id=(select auth.uid()))); create policy progress_update on public.reading_progress for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy progress_delete on public.reading_progress for delete to authenticated using ((select auth.uid())=user_id);
create policy categories_select on public.categories for select to authenticated using ((select auth.uid())=user_id); create policy categories_insert on public.categories for insert to authenticated with check ((select auth.uid())=user_id); create policy categories_update on public.categories for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy categories_delete on public.categories for delete to authenticated using ((select auth.uid())=user_id);
create policy manga_categories_select on public.manga_categories for select to authenticated using ((select auth.uid())=user_id); create policy manga_categories_insert on public.manga_categories for insert to authenticated with check ((select auth.uid())=user_id and exists(select 1 from public.mangas m where m.id=manga_id and m.user_id=(select auth.uid())) and exists(select 1 from public.categories c where c.id=category_id and c.user_id=(select auth.uid()))); create policy manga_categories_update on public.manga_categories for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy manga_categories_delete on public.manga_categories for delete to authenticated using ((select auth.uid())=user_id);
create policy subscriptions_select on public.push_subscriptions for select to authenticated using ((select auth.uid())=user_id); create policy subscriptions_insert on public.push_subscriptions for insert to authenticated with check ((select auth.uid())=user_id); create policy subscriptions_update on public.push_subscriptions for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy subscriptions_delete on public.push_subscriptions for delete to authenticated using ((select auth.uid())=user_id);
create policy notifications_select on public.notifications for select to authenticated using ((select auth.uid())=user_id); create policy notifications_insert on public.notifications for insert to authenticated with check ((select auth.uid())=user_id); create policy notifications_update on public.notifications for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy notifications_delete on public.notifications for delete to authenticated using ((select auth.uid())=user_id);
create policy logs_select on public.manga_check_logs for select to authenticated using ((select auth.uid())=user_id); create policy logs_insert on public.manga_check_logs for insert to authenticated with check ((select auth.uid())=user_id); create policy logs_update on public.manga_check_logs for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy logs_delete on public.manga_check_logs for delete to authenticated using ((select auth.uid())=user_id);
create policy settings_select on public.user_settings for select to authenticated using ((select auth.uid())=user_id); create policy settings_insert on public.user_settings for insert to authenticated with check ((select auth.uid())=user_id); create policy settings_update on public.user_settings for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy settings_delete on public.user_settings for delete to authenticated using ((select auth.uid())=user_id);
commit;
